name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push, pull]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: linter
        run: npm run lint
      - name: start app
        run: npm start &
      - name: build project
        run: npm run build
      - name: unit tests
        run: npm run test
      - name: Set up XVFB (Virtual Display)
        run: sudo apt-get install xvfb
      - name: e2e tests
        run: xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" npm run test:e2e